package liou.rayyuan.ebooksearchtaiwan.ui

import androidx.compose.ui.unit.dp

val SEARCH_LIST_PADDING_HORIZONTAL = 8.dp
val CAMERA_PREVIEW_BOTTOM_RESULT_HEIGHT = 150.dp
val CAMERA_PREVIEW_BOTTOM_RESULT_LAND_WIDTH = 150.dp

val LIST_BOOK_COVER_WIDTH = 96.dp
val LIST_BOOK_COVER_HEIGHT = 133.dp

val SEARCH_RECORDS_MAX_HEIGHT = 300.dp
val SEARCH_RECORDS_ITEM_HEIGHT = 48.dp

val ROUND_CORNER = 10.dp
val IMAGE_ROUND_CORNER = 4.dp
